
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Nov 16 14:42:36 CET 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 2;
  public static final int VARIABLE = 9;
  public static final int EOF = 0;
  public static final int IMP = 5;
  public static final int error = 1;
  public static final int RPAREN = 8;
  public static final int BIIMP = 6;
  public static final int NEG = 4;
  public static final int LPAREN = 7;
  public static final int OR = 3;
}

